-- ListingOverrides.lua
-- Auto-generated by bin/catdb_zone_emit.py from .warehouse/Sources (12.1.0.69497)
-- Do not edit by hand; re-run: python bin/catdb_zone_emit.py
-- Scaffold hook: ns:RegisterListingOverrides
local _, ns = ...

ns:RegisterListingOverrides({
	forceHide={
		["1:63"]=true,
	},
	forceShow={
		["1:760"]=true,
	},
})
