local _, ns = ...

local OneWoW_GUI = OneWoW_GUI

local noArgs = {}
local unitSpellCastCommonArgs = { "unit", "castGUID", "spellID", "castBarID" }
local itemLockCommonArgs = { "bagOrSlotIdx", "slotIdx" }

ns.Constants = {
    -- Error logger: EventRegistry name for internal subscribers (e.g. future EventMonitor correlation)
    ERROR_CAPTURE_EVENT = "OneWoW_DevTool.ErrorCaptured",
    -- Fired from UpdateErrorBadge when current-session errors appear or clear.
    ERROR_ALERT_EVENT = "OneWoW_DevTool.ErrorAlert",
    -- Token-bucket refill rate (errors per second) before throttling capture
    ERROR_LOGGER_ERRORS_PER_SEC = 10,
    ERROR_LOGGER_ALERT_SOUND_FILE = OneWoW_GUI.Constants.MEDIA_BASE .. "OneWoW_Utility_DevTool\\devtools-error.ogg",
    -- Standalone !BugGrabber addon folder name (ADDON_LOADED arg); not embedded in DevTool
    BUGGRABBER_STANDALONE_ADDON = "!BugGrabber",

    EVENT_SELECTOR_CUSTOM_BUFFER = 100,

    -- Event viewer color keys; string = OneWoW_GUI theme key, table = {r,g,b,a} for colors not in theme
    EVENT_VIEWER_COLORS = {
        TIMESTAMP = "TEXT_MUTED",
        EVENT_NAME = "TEXT_ACCENT",
        ARG_DEFAULT = "TEXT_PRIMARY",
        UNIT = { 0.4, 0.6, 0.9, 1 },
        SECRET = { 1, 0.4, 0.4, 1 },
    },
    EVENT_COLLAPSE_WINDOW = 0.2,

    -- Event viewer row layout (pixels)
    EVENT_VIEWER_ROW_HEIGHT = 14,
    EVENT_VIEWER_COL_EVENT = 280,
    EVENT_VIEWER_COL_ARGS = 260,

    -- Argument names per event (index = arg position); reference: warcraft.wiki.gg/wiki/Events
    EVENT_ARG_NAMES = {
        PLAYER_ENTERING_WORLD = {"isInitialLogin", "isReload"},
        PLAYER_LEAVING_WORLD = noArgs,
        PLAYER_LOGIN = noArgs,
        PLAYER_LOGOUT = noArgs,
        ZONE_CHANGED = noArgs,
        ZONE_CHANGED_NEW_AREA = noArgs,
        ZONE_CHANGED_INDOORS = noArgs,
        PLAYER_REGEN_DISABLED = noArgs,
        PLAYER_REGEN_ENABLED = noArgs,
        UNIT_AURA = { "unit", "info" },
        UNIT_POWER_UPDATE = { "unit", "type" },
        UNIT_HEALTH = { "unit" },
        BAG_UPDATE = { "bagID" },
        BAG_UPDATE_DELAYED = noArgs,
        BAG_UPDATE_COOLDOWN = noArgs,
        ITEM_LOCKED = itemLockCommonArgs,
        ITEM_LOCK_CHANGED = itemLockCommonArgs,
        ITEM_UNLOCKED = itemLockCommonArgs,
        GET_ITEM_INFO_RECEIVED = { "itemID", "success" },
        INVENTORY_SEARCH_UPDATE = noArgs,
        CHAT_MSG_SAY = {"message"},
        CHAT_MSG_YELL = {"message"},
        CHAT_MSG_WHISPER = {"message", "sender"},
        CHAT_MSG_PARTY = {"message"},
        CHAT_MSG_GUILD = {"message"},
        CHAT_MSG_OFFICER = {"message"},
        CHAT_MSG_RAID = {"message"},
        CHAT_MSG_SYSTEM = {"message"},
        ADDON_LOADED = {"name", "hasBindings"},
        VARIABLES_LOADED = noArgs,
        QUEST_ACCEPTED = {"questID"},
        QUEST_TURNED_IN = {"questID", "xp", "money"},
        QUEST_LOG_UPDATE = noArgs,
        QUEST_REMOVED = {"questID", "wasReplay"},
        QUEST_DETAIL = {"startItemID"},
        QUEST_COMPLETE = noArgs,
        QUEST_PROGRESS = noArgs,
        QUEST_GREETING = noArgs,
        QUEST_WATCH_LIST_CHANGED = {"questID", "added"},
        SUPER_TRACKING_CHANGED = noArgs,
        MERCHANT_SHOW = noArgs,
        MERCHANT_CLOSED = noArgs,
        MERCHANT_UPDATE = noArgs,
        MAIL_INBOX_UPDATE = noArgs,
        MAIL_SHOW = noArgs,
        MAIL_CLOSED = noArgs,
        AUCTION_HOUSE_SHOW = noArgs,
        AUCTION_HOUSE_CLOSED = noArgs,
        LOOT_OPENED = {"autoLoot", "isFromItem"},
        LOOT_CLOSED = noArgs,
        LOOT_READY = {"autoLoog"},
        START_LOOT_ROLL = {"rollID", "rollTime", "lootHandle"},
        TRADE_SHOW = noArgs,
        TRADE_CLOSED = noArgs,
        BANKFRAME_OPENED = noArgs,
        BANKFRAME_CLOSED = noArgs,
        PLAYERBANKSLOTS_CHANGED = {"slot"},
        PLAYER_ACCOUNT_BANK_TAB_SLOTS_CHANGED = {"slot"},
        TAXIMAP_OPENED = {"system"},
        TAXIMAP_CLOSED = noArgs,
        GOSSIP_SHOW = {"uiTextureKit"},
        GOSSIP_CLOSED = {"interactionIsContinuing"},
        TRADE_SKILL_SHOW = noArgs,
        TRADE_SKILL_CLOSE = noArgs,
        TRANSMOGRIFY_OPEN = noArgs,
        TRANSMOGRIFY_CLOSE = noArgs,
        TRANSMOGRIFY_SUCCESS = {"location"},
        TRANSMOGRIFY_UPDATE = noArgs,
        VIEWED_TRANSMOG_OUTFIT_CHANGED = noArgs,
        VIEWED_TRANSMOG_OUTFIT_SITUATIONS_CHANGED = noArgs,
        VIEWED_TRANSMOG_OUTFIT_SLOT_REFRESH = noArgs,
        VIEWED_TRANSMOG_OUTFIT_SLOT_SAVE_SUCCESS = {"slot", "type", "option"},
        TRANSMOG_SEARCH_UPDATED = {"searchType", "collectionType"},
        TRANSMOG_COLLECTION_UPDATED = {"collectionIdx", "modID", "itemAppearanceID", "reason"},
        ITEM_SEARCH_RESULTS_UPDATED = {"itemKey", "newAuctionID"},
        COMMODITY_SEARCH_RESULTS_UPDATED = {"itemID"},
        AUCTION_HOUSE_AUCTION_CREATED = {"auctionID"},
        AUCTION_HOUSE_THROTTLED_SYSTEM_READY = noArgs,
        BLACK_MARKET_OPEN = noArgs,
        BLACK_MARKET_BID_RESULT = {"marketID", "resultCode"},
        CRAFTINGORDERS_DISPLAY_CRAFTER_FULFILLED_MSG = {"orderTypeString", "itemNameString", "playerNameString", "tipAmount", "quantityCrafted"},
        PLAYER_MONEY = noArgs,
        PLAYER_DEAD = noArgs,
        PLAYER_UNGHOST = noArgs,
        PLAYER_EQUIPMENT_CHANGED = {"equipmentSlot", "hasCurrent"},
        UPDATE_INVENTORY_DURABILITY = noArgs,
        GUILDBANKFRAME_OPENED = noArgs,
        GUILDBANKFRAME_CLOSED = noArgs,
        GUILDBANK_UPDATE_MONEY = noArgs,
        GUILDBANKBAGSLOTS_CHANGED = noArgs,
        GUILDBANK_UPDATE_TABS = noArgs,
        TRADE_ACCEPT_UPDATE = {"playerAccepted", "targetAccepted"},
        TRADE_MONEY_CHANGED = noArgs,
        TRADE_PLAYER_ITEM_CHANGED = {"tradeSlotIdx"},
        TRADE_TARGET_ITEM_CHANGED = {"tradeSlotIdx"},
        UI_INFO_MESSAGE = {"errorType", "message"},
        UI_ERROR_MESSAGE = {"errorType", "message"},
        TRAIT_CONFIG_COMMIT_FAILED = noArgs,
        TRAIT_COND_INFO_CHANGED = {"condID"},
        TRAIT_CONFIG_CREATED = {"configInfo"},
        TRAIT_CONFIG_DELETED = {"configID"},
        TRAIT_CONFIG_LIST_UPDATED = noArgs,
        TRAIT_CONFIG_UPDATED = {"configID"},
        TRAIT_NODE_CHANGED = {"nodeID"},
        TRAIT_NODE_CHANGED_PARTIAL = {"ID", "info"},
        TRAIT_NODE_ENTRY_UPDATED = {"nodeEntryID"},
        TRAIT_SUB_TREE_CHANGED = {"subTreeID"},
        TRAIT_SYSTEM_INTERACTION_STARTED = {"treeID"},
        TRAIT_SYSTEM_NPC_CLOSED = noArgs,
        TRAIT_TREE_CHANGED = {"treeID"},
        TRAIT_TREE_CURRENCY_INFO_UPDATED = {"treeID"},
        TRY_PURCHASE_TO_NODE_PARTIAL_SUCCESS = {"nodeFinishedOn"},
        ACTIVE_COMBAT_CONFIG_CHANGED = {"configID"},
        SELECTED_LOADOUT_CHANGED = noArgs,
        SPECIALIZATION_CHANGE_CAST_FAILED = noArgs,
        STARTER_BUILD_ACTIVATION_FAILED = noArgs,
        TALENTS_INVOLUNTARILY_RESET = {"isPetTalents"},
        PORTRAITS_UPDATED = noArgs,
        PLAYER_LEVEL_UP = {"level", "healthDelta", "powerDelta", "numNewTalents", "numNewPvpTalentSlots", "strengthDelta", "agilityDelta", "staminaDelta", "intellectDelta", "spiritDelta"},
        PLAYER_TARGET_CHANGED = noArgs,
        UNIT_SPELLCAST_START = unitSpellCastCommonArgs,
        UNIT_SPELLCAST_STOP = unitSpellCastCommonArgs,
        UNIT_SPELLCAST_CHANNEL_START = unitSpellCastCommonArgs,
        UNIT_SPELLCAST_CHANNEL_STOP = unitSpellCastCommonArgs,
        UNIT_SPELLCAST_SUCCEEDED = unitSpellCastCommonArgs,
        SPELL_UPDATE_COOLDOWN = {"spellID", "baseSpellID", "category", "startRecoveryCategory"},
        SPELLS_CHANGED = noArgs,
        CHAT_MSG_CHANNEL = {"message"},
        BAG_OPEN = {"bagID"},
        BAG_CLOSED = {"bagID"},
        LOOT_SLOT_CHANGED = {"lootSlot"},
        GROUP_ROSTER_UPDATE = noArgs,
        PLAYER_SPECIALIZATION_CHANGED = {"unitTarget"},
        CURRENCY_DISPLAY_UPDATE = {"currencyType", "quantity", "quantityChange", "quantityGainSource", "destroyReason"},
        UPDATE_BINDINGS = noArgs,
        ENCOUNTER_START = {"encounterID", "encounterName", "difficultyID", "groupSize"},
        ENCOUNTER_END = {"encounterID", "encounterName", "difficultyID", "groupSize", "success"},
        UPDATE_INSTANCE_INFO = noArgs,
        WEEKLY_REWARDS_UPDATE = noArgs,
        NEW_RECIPE_LEARNED = {"recipeID", "recipeLevel", "baseRecipeID"},
        CHALLENGE_MODE_COMPLETED = noArgs,
        MOUNT_JOURNAL_USABILITY_CHANGED = noArgs,
    },

    -- Reference: https://warcraft.wiki.gg/wiki/Events
    COMMON_EVENTS = {
        "PLAYER_ENTERING_WORLD", "PLAYER_LEAVING_WORLD", "PLAYER_LOGIN", "PLAYER_LOGOUT",
        "ZONE_CHANGED", "ZONE_CHANGED_NEW_AREA", "ZONE_CHANGED_INDOORS",
        "PLAYER_REGEN_DISABLED", "PLAYER_REGEN_ENABLED",
        "UNIT_HEALTH", "UNIT_POWER_UPDATE", "UNIT_AURA",
        "BAG_UPDATE", "BAG_UPDATE_DELAYED", "BAG_UPDATE_COOLDOWN", "ITEM_LOCKED", "ITEM_LOCK_CHANGED", "ITEM_UNLOCKED",
        "GET_ITEM_INFO_RECEIVED", "INVENTORY_SEARCH_UPDATE",
        "CHAT_MSG_SAY", "CHAT_MSG_YELL", "CHAT_MSG_WHISPER", "CHAT_MSG_PARTY",
        "CHAT_MSG_GUILD", "CHAT_MSG_OFFICER", "CHAT_MSG_RAID", "CHAT_MSG_SYSTEM",
        "ADDON_LOADED", "VARIABLES_LOADED",
        "QUEST_ACCEPTED", "QUEST_TURNED_IN", "QUEST_LOG_UPDATE", "QUEST_REMOVED",
        "QUEST_DETAIL", "QUEST_COMPLETE", "QUEST_PROGRESS", "QUEST_GREETING",
        "QUEST_WATCH_LIST_CHANGED", "SUPER_TRACKING_CHANGED",
        "MERCHANT_SHOW", "MERCHANT_CLOSED", "MERCHANT_UPDATE",
        "MAIL_INBOX_UPDATE", "MAIL_SHOW", "MAIL_CLOSED",
        "AUCTION_HOUSE_SHOW", "AUCTION_HOUSE_CLOSED",
        "LOOT_OPENED", "LOOT_CLOSED", "LOOT_READY", "START_LOOT_ROLL",
        "TRADE_SHOW", "TRADE_CLOSED",
        "BANKFRAME_OPENED", "BANKFRAME_CLOSED",
        "PLAYERBANKSLOTS_CHANGED", "PLAYER_ACCOUNT_BANK_TAB_SLOTS_CHANGED",
        "TAXIMAP_OPENED", "TAXIMAP_CLOSED",
        "GOSSIP_SHOW", "GOSSIP_CLOSED",
        "TRADE_SKILL_SHOW", "TRADE_SKILL_CLOSE",
        "TRANSMOGRIFY_OPEN", "TRANSMOGRIFY_CLOSE", "TRANSMOGRIFY_SUCCESS", "TRANSMOGRIFY_UPDATE",
        "VIEWED_TRANSMOG_OUTFIT_CHANGED", "VIEWED_TRANSMOG_OUTFIT_SITUATIONS_CHANGED",
        "VIEWED_TRANSMOG_OUTFIT_SLOT_REFRESH", "VIEWED_TRANSMOG_OUTFIT_SLOT_SAVE_SUCCESS",
        "TRANSMOG_SEARCH_UPDATED", "TRANSMOG_COLLECTION_UPDATED",
        "ITEM_SEARCH_RESULTS_UPDATED", "COMMODITY_SEARCH_RESULTS_UPDATED",
        "AUCTION_HOUSE_AUCTION_CREATED", "AUCTION_HOUSE_THROTTLED_SYSTEM_READY",
        "BLACK_MARKET_OPEN", "BLACK_MARKET_BID_RESULT",
        "CRAFTINGORDERS_DISPLAY_CRAFTER_FULFILLED_MSG",
        "PLAYER_MONEY", "PLAYER_DEAD", "PLAYER_UNGHOST",
        "PLAYER_EQUIPMENT_CHANGED", "UPDATE_INVENTORY_DURABILITY",
        "GUILDBANKFRAME_OPENED", "GUILDBANKFRAME_CLOSED", "GUILDBANK_UPDATE_MONEY",
        "GUILDBANKBAGSLOTS_CHANGED", "GUILDBANK_UPDATE_TABS",
        "TRADE_ACCEPT_UPDATE", "TRADE_MONEY_CHANGED",
        "TRADE_PLAYER_ITEM_CHANGED", "TRADE_TARGET_ITEM_CHANGED",
        "UI_INFO_MESSAGE", "UI_ERROR_MESSAGE",
        "TRAIT_CONFIG_COMMIT_FAILED", "TRAIT_COND_INFO_CHANGED", "TRAIT_CONFIG_CREATED",
        "TRAIT_CONFIG_DELETED", "TRAIT_CONFIG_LIST_UPDATED", "TRAIT_CONFIG_UPDATED",
        "TRAIT_NODE_CHANGED", "TRAIT_NODE_CHANGED_PARTIAL", "TRAIT_NODE_ENTRY_UPDATED",
        "TRAIT_SUB_TREE_CHANGED", "TRAIT_SYSTEM_INTERACTION_STARTED", "TRAIT_SYSTEM_NPC_CLOSED",
        "TRAIT_TREE_CHANGED", "TRAIT_TREE_CURRENCY_INFO_UPDATED", "TRY_PURCHASE_TO_NODE_PARTIAL_SUCCESS",
        "ACTIVE_COMBAT_CONFIG_CHANGED", "SELECTED_LOADOUT_CHANGED", "SPECIALIZATION_CHANGE_CAST_FAILED",
        "STARTER_BUILD_ACTIVATION_FAILED", "TALENTS_INVOLUNTARILY_RESET",
        "PORTRAITS_UPDATED", "PLAYER_LEVEL_UP",
        "PLAYER_TARGET_CHANGED",
        "UNIT_SPELLCAST_START", "UNIT_SPELLCAST_STOP",
        "UNIT_SPELLCAST_CHANNEL_START", "UNIT_SPELLCAST_CHANNEL_STOP",
        "UNIT_SPELLCAST_SUCCEEDED",
        "SPELL_UPDATE_COOLDOWN", "SPELLS_CHANGED",
        "CHAT_MSG_CHANNEL",
        "BAG_OPEN", "BAG_CLOSED",
        "LOOT_SLOT_CHANGED",
        "GROUP_ROSTER_UPDATE",
        "PLAYER_SPECIALIZATION_CHANGED",
        "CURRENCY_DISPLAY_UPDATE",
        "UPDATE_BINDINGS",
        "ENCOUNTER_START", "ENCOUNTER_END",
        "UPDATE_INSTANCE_INFO", "WEEKLY_REWARDS_UPDATE", "NEW_RECIPE_LEARNED",
        "CHALLENGE_MODE_COMPLETED", "MOUNT_JOURNAL_USABILITY_CHANGED",
    },

    -- Preset hex swatches for Color Tools tab (display names via locale nameKey)
    COLOR_TOOLS_COMMON = {
        { hex = "FFFFFF", nameKey = "COLOR_TOOLS_NAME_WHITE" },
        { hex = "000000", nameKey = "COLOR_TOOLS_NAME_BLACK" },
        { hex = "FF0000", nameKey = "COLOR_TOOLS_NAME_RED" },
        { hex = "00FF00", nameKey = "COLOR_TOOLS_NAME_GREEN" },
        { hex = "0000FF", nameKey = "COLOR_TOOLS_NAME_BLUE" },
        { hex = "FFFF00", nameKey = "COLOR_TOOLS_NAME_YELLOW" },
        { hex = "00FFFF", nameKey = "COLOR_TOOLS_NAME_CYAN" },
        { hex = "FF00FF", nameKey = "COLOR_TOOLS_NAME_MAGENTA" },
        { hex = "FFA500", nameKey = "COLOR_TOOLS_NAME_ORANGE" },
        { hex = "800080", nameKey = "COLOR_TOOLS_NAME_PURPLE" },
        { hex = "FFD700", nameKey = "COLOR_TOOLS_NAME_GOLD" },
        { hex = "C0C0C0", nameKey = "COLOR_TOOLS_NAME_SILVER" },
    },

    -- Main window / cross-tab UI tuning
    DEVTOOL_UI = {
        MAIN_FRAME_DEFAULT_WIDTH = 750,
        MAIN_FRAME_DEFAULT_HEIGHT = 450,
        MAIN_FRAME_RESIZE_CAP = 0.95,
        TAB_GAP = 4,
        TAB_HEIGHT = 28,
        -- Fonts / Textures copy toolbar: FONT_COPY_ROW_LABEL + short action buttons (no "Copy" per button).
        -- Textures: FONT_BTN_COPY_NAME + TEXTURE_BTN_COPY_SNIPPET + TEXTURE_BTN_COPY_COORDS.
        FONT_BROWSER_LEFT_PANE_DEFAULT_WIDTH = 280,
        FONT_BROWSER_LEFT_PANE_MIN_WIDTH = 180,
        FONT_BROWSER_RIGHT_PANE_MIN_WIDTH = 340,
        FONT_BROWSER_LIST_ROW_HEIGHT = 20,
        FONT_BROWSER_LIST_VISIBLE_ROWS = 40,
        FONT_BROWSER_PREVIEW_BG_HEIGHT = 100,
        -- Neutral dark slate; readable for black, white, gold, grey text. Override nil to use theme BG_TERTIARY.
        FONT_BROWSER_PREVIEW_BG = { 68/255, 71/255, 74/255, 1.0 },
        FONT_BROWSER_PREVIEW_SWATCH_SIZE = 18,
        -- Extra vertical space below the last workspace row (breathing room; does not add controls).
        FONT_BROWSER_WORKSPACE_EXTRA_HEIGHT = 40,
        -- Fixed width for right-aligned workspace labels (accommodates longest locale, e.g. German).
        FONT_BROWSER_LABEL_COLUMN_WIDTH = 100,
        FONT_BROWSER_BOOKMARK_ICON_SIZE = 14,
        FONT_BROWSER_BOOKMARK_ICON_RIGHT_PAD = 8,
        FONT_BROWSER_BOOKMARK_ICON_TEXT_GAP = 4,
        FRAME_INSPECTOR_LEFT_DEFAULT_WIDTH = 350,
        FRAME_INSPECTOR_LEFT_MIN_WIDTH = 350,
        FRAME_INSPECTOR_RIGHT_MIN_WIDTH = 300,
        FRAME_INSPECTOR_DIVIDER_WIDTH = 6,
        EVENT_SELECTOR_WIDTH = 600,
        EVENT_SELECTOR_HEIGHT = 500,
        EVENT_IMPORT_WIDTH = 650,
        EVENT_IMPORT_HEIGHT = 480,
        EVENT_MONITOR_MAX_ROWS = 201,
        MONITOR_LIST_ROW_HEIGHT = 20,
        MONITOR_MAX_ROWS = 60,
        MONITOR_COL_AP_NARROW = 40,
        MONITOR_COL_AP_MED = 48,
        MONITOR_LIST_RIGHT_GUTTER = 14,
        TEXTURE_LIST_BUTTON_HEIGHT = 18,
        TEXTURE_PREVIEW_BASE_SIZE = 256,
        TEXTURE_ZOOM_IN_FACTOR = 1.2,
        TEXTURE_ZOOM_OUT_FACTOR = 0.8,
        TEXTURE_ZOOM_MIN = 0.03,
        TEXTURE_ZOOM_MAX = 4.0,
        -- After fitting the sheet in the clip, multiply zoom by this; 0.8 => 80% in the UI (100% = full fit after Reset).
        TEXTURE_SHEET_INITIAL_ZOOM_MULTIPLIER = 0.8,
        -- Manhattan distance (UI units) before a left-drag counts as pan (overlay clicks use shorter drags to select).
        TEXTURE_SHEET_PAN_CLICK_THRESHOLD = 4,
        -- Space reserved below texture preview for details + collected list + copy row (pixels from bottom of right panel).
        TEXTURE_PREVIEW_BOTTOM_RESERVE = 235,
        TEXTURE_COLLECTED_PANE_HEIGHT = 96,
        TEXTURE_SHEET_OVERLAY_COLLECTED_FILL_ALPHA = 0.16,
        TEXTURE_SHEET_OVERLAY_COLLECTED_BORDER_ALPHA = 0.9,
        TEXTURE_BROWSER_LIST_ROW_HEIGHT = 22,
        TEXTURE_BROWSER_LIST_VISIBLE_ROWS = 40,
        -- Resizable list / preview split (CreateVerticalPaneResizer).
        TEXTURE_BROWSER_LEFT_PANE_DEFAULT_WIDTH = 300,
        TEXTURE_BROWSER_LEFT_PANE_MIN_WIDTH = 200,
        TEXTURE_BROWSER_RIGHT_PANE_MIN_WIDTH = 260,
        GLOBALS_BROWSER_LIST_ROW_HEIGHT = 20,
        GLOBALS_BROWSER_LIST_VISIBLE_ROWS = 40,
        GLOBALS_BROWSER_LEFT_PANE_DEFAULT_WIDTH = 300,
        GLOBALS_BROWSER_LEFT_PANE_MIN_WIDTH = 200,
        GLOBALS_BROWSER_RIGHT_PANE_MIN_WIDTH = 320,
        SOUND_BROWSER_LIST_ROW_HEIGHT = 22,
        SOUND_BROWSER_LIST_VISIBLE_ROWS = 40,
        SOUND_BROWSER_LEFT_PANE_DEFAULT_WIDTH = 300,
        SOUND_BROWSER_LEFT_PANE_MIN_WIDTH = 200,
        SOUND_BROWSER_RIGHT_PANE_MIN_WIDTH = 260,
        SOUND_BROWSER_BOTTOM_COPY_STRIP_HEIGHT = 42,
        SOUND_BROWSER_MANUAL_PANEL_HEIGHT = 92,
        -- Optional override for CreateVerticalPaneResizer splitPadding (default: divider width + 10).
        -- TEXTURE_BROWSER_SPLIT_PADDING = 18,
        -- Bookmark icon on list rows (texture layer, right-aligned).
        TEXTURE_BROWSER_BOOKMARK_ICON_SIZE = 14,
        TEXTURE_BROWSER_BOOKMARK_ICON_RIGHT_PAD = 8,
        TEXTURE_BROWSER_BOOKMARK_ICON_TEXT_GAP = 4,
        -- Sheet grid: cell borders; selected cell gets thicker edge + tint (see TextureViewerTab refreshSheetOverlays).
        TEXTURE_SHEET_OVERLAY_EDGE_NORMAL = 1,
        TEXTURE_SHEET_OVERLAY_EDGE_SELECTED = 3,
        TEXTURE_SHEET_OVERLAY_SELECTED_FILL_ALPHA = 0.26,
        TEXTURE_SHEET_OVERLAY_UNSELECTED_BORDER_ALPHA = 0.55,
        TEXTURE_SHEET_OVERLAY_SELECTED_LEVEL_OFFSET = 10,
        TEXTURE_SHEET_OVERLAY_NORMAL_LEVEL_OFFSET = 1,
        -- Star on bookmarked cells in sheet preview (clicks still hit parent overlay button).
        TEXTURE_SHEET_PREVIEW_BOOKMARK_ICON_SIZE = 12,
        TEXTURE_SHEET_PREVIEW_BOOKMARK_ICON_INSET = 2,
        COLOR_PICKER_PANEL_WIDTH = 280,
        COLOR_PICKER_PANEL_HEIGHT = 297,
        COLOR_CLASS_PANEL_MIN_WIDTH = 200,
        COLOR_TOOLS_PICKER_TOP_PADDING = 10,
        COLOR_TOOLS_PICKER_VERTICAL_GAP = 20,
        COLOR_TOOLS_ROW_HEIGHT = 25,
        COLOR_TOOLS_ROW_SPACING = 27,
        EDITOR_LEFT_PANE_DEFAULT_WIDTH = 220,
        EDITOR_LEFT_PANE_MIN_WIDTH = 160,
        EDITOR_RIGHT_PANE_MIN_WIDTH = 400,
        EDITOR_DIVIDER_WIDTH = 6,
        EDITOR_OUTPUT_DEFAULT_HEIGHT = 120,
        EDITOR_OUTPUT_MIN_HEIGHT = 60,
        EDITOR_EDITOR_MIN_HEIGHT = 100,
        EDITOR_GUTTER_MIN_WIDTH = 36,
        EDITOR_DEFAULT_FONT_SIZE = 12,
        EDITOR_DEFAULT_INDENT = 3,
        EDITOR_SNIPPET_ROW_HEIGHT = 20,
        EDITOR_CATEGORY_ROW_HEIGHT = 22,
        EDITOR_MAX_SNIPPET_SIZE = 51200,
        EDITOR_COLORIZE_DEBOUNCE = 0.2,
        EDITOR_UNDO_DEBOUNCE = 0.5,
        EDITOR_STATUS_BAR_HEIGHT = 18,
        EDITOR_SYNTAX_CHECK_DEBOUNCE = 5,
        EDITOR_STATUS_CLEAR_DELAY = 5,
    },

    SOUND_CVAR_ENABLE_MUSIC = "Sound_EnableMusic",
    SOUND_CVAR_ENABLE_AMBIENCE = "Sound_EnableAmbience",
    SOUND_PATH_PREFIX = "sound/",

    MONITOR_PRESET = {
        BALANCED = "balanced",
        MEMORY_DIG = "memory_dig",
        CPU_SPIKES = "cpu_spikes",
        MINIMAL = "minimal",
        ENGINE_PROFILER = "engine_profiler",
    },
    MONITOR_SORT_NAME = 1,
    MONITOR_SORT_MEMORY = 2,
    MONITOR_SORT_CPU_SESSION = 3,
    MONITOR_SORT_MEM_DELTA = 4,
    MONITOR_SORT_MEM_PEAK = 5,
    MONITOR_SORT_CPU_RECENT = 6,
    MONITOR_SORT_CPU_MS = 7,
    MONITOR_SORT_MEM_PCT = 8,
    MONITOR_SORT_CPU_PCT = 9,
    MONITOR_SORT_AP_SESSION = 10,
    MONITOR_SORT_AP_RECENT = 11,
    MONITOR_SORT_AP_PEAK = 12,
    MONITOR_SORT_AP_OVER1 = 13,
    MONITOR_SORT_AP_OVER5 = 14,
    MONITOR_SORT_AP_OVER10 = 15,
    MONITOR_SORT_AP_OVER50 = 16,
    MONITOR_SORT_AP_OVER100 = 17,
    MONITOR_SORT_AP_OVER500 = 18,
    MONITOR_SORT_AP_OVER1000 = 19,
    MONITOR_SORT_AP_SPIKE = 20,
    MONITOR_MAX_PINNED_POPOUTS = 4,
    MONITOR_AP_SPIKE_WEIGHTS = { 1, 5, 10, 50, 100 },
    MONITOR_PRESET_DEFAULT_SORT = {
        balanced = -2,
        memory_dig = -4,
        cpu_spikes = -6,
        minimal = -2,
        engine_profiler = -20,
    },

    -- Reference: https://warcraft.wiki.gg/wiki/Widget_script_handlers
    COMMON_SCRIPTS = {
        "OnAnimFinished", "OnAnimStarted", "OnArrowPressed", "OnAttributeChanged",
        "OnChar", "OnCharComposition", "OnClick", "OnColorSelect", "OnCooldownDone",
        "OnCursorChanged", "OnDisable", "OnDoubleClick", "OnDragStart", "OnDragStop",
        "OnDressModel", "OnEditFocusGained", "OnEditFocusLost", "OnEnable",
        "OnEnter", "OnEnterPressed", "OnEscapePressed", "OnEvent", "OnFinished",
        "OnGamePadButtonDown", "OnGamePadButtonUp", "OnGamePadStick",
        "OnHide", "OnHorizontalScroll", "OnHyperlinkClick", "OnHyperlinkEnter", "OnHyperlinkLeave",
        "OnInputLanguageChanged", "OnKeyDown", "OnKeyUp", "OnLeave", "OnLoad",
        "OnLoop", "OnMinMaxChanged", "OnModelCleared", "OnModelLoaded", "OnModelLoading",
        "OnMouseDown", "OnMouseUp", "OnMouseWheel", "OnMovieFinished", "OnPanFinished",
        "OnPause", "OnPlay", "OnReceiveDrag", "OnScrollRangeChanged", "OnShow",
        "OnSizeChanged", "OnSpacePressed", "OnStop", "OnTabPressed", "OnTextChanged",
        "OnTextSet", "OnTooltipCleared", "OnTooltipSetDefaultAnchor", "OnTooltipSetFramestack",
        "OnUiMapChanged", "OnUpdate", "OnValueChanged", "OnVerticalScroll",
        "PostClick", "PreClick",
    },
}
